LambdaTest/test-at-scale

- README.md
NA
updated broken links for readme files
> updated readme links

- config/loader.go
N/A
For public repos, gitToken is not required. Allowing the user to supply an empty token.
This is tested on local synapse
> Removed empty GitToken validation

- README.md
updated readme file for miss-spelling of LambdaTest
> Updated LambdaTest names at few places

- .sample.synapse.json
- Makefile
NA.
Added default GitToken config and default repo config.
> updated default config

- .github/workflows/main.yml
N/A
Better CI logging for debug-ability for devs.
Testing CI on current branch
> Developer Efficiency: Improved CI logging

- README.md
> Updated hyperlinks

- README.md
> Updations in the docs

- README.md
> Updates in the Readme

- README.md
> Update in Readme for  product page and discord 

- .github/workflows/main.yml
Added support for CI/CD
This PR will add support for CI/CD
- This CI/CD will work on the following branch.
- dev: images will be pushed to lambdatest/nucleus:dev, lambdatest/synapse:dev
- stage: images will be pushed to lambdatest/nucleus:stage, lambdatest/synapse:stage
- master: images will be pushed to lambdatest/nucleus:prod, lambdatest/synapse:prod
- v1.0.0: images will be pushed to lambdatest/nucleus:v1.0.0, lambdatest/synapse:v1.0.0
- NA
> added support for CI/CD

- pkg/testdiscoveryservice/testdiscovery.go
Fixing bug in discovery mode where are smart selection is not working.
> bug fix in discovery mode

- README.md
> Added contributions badge

- README.md
- build/nucleus/Dockerfile
- build/nucleus/entrypoint.sh
- config/nucleusmodel.go
- pkg/cachemanager/cachemanager.go
- pkg/core/interfaces.go
- pkg/core/lifecycle.go
- pkg/core/models.go
- pkg/diffmanager/setup.go
- pkg/fileutils/fileutils.go
- pkg/global/nucleusconstants.go
- pkg/payloadmanager/setup.go
- pkg/runner/docker/config.go
- pkg/service/coverage/coverage.go
- pkg/testdiscoveryservice/testdiscovery.go
- pkg/testexecutionservice/testexecution.go
- pkg/zstd/zstd.go
> stage code update (master)

- .github/workflows/main.yml
updated branching strategy
NA
Updated the branches for CI/CD.
NA
> updated ci/cd

- .github/workflows/main.yml
- README.md
- build/nucleus/Dockerfile
- build/nucleus/entrypoint.sh
- config/nucleusmodel.go
- pkg/cachemanager/cachemanager.go
- pkg/core/interfaces.go
- pkg/core/lifecycle.go
- pkg/core/models.go
- pkg/diffmanager/setup.go
- pkg/fileutils/fileutils.go
- pkg/global/nucleusconstants.go
- pkg/payloadmanager/setup.go
- pkg/runner/docker/config.go
- pkg/service/coverage/coverage.go
- pkg/testdiscoveryservice/testdiscovery.go
- pkg/testexecutionservice/testexecution.go
- pkg/zstd/zstd.go
> Merge dev to beta

- .sample.synapse.json
- config/default.go
- pkg/lumber/zap.go
Logging Fixes causing timestamps to not get outputted
> logging timestamps and standard log format

- .github/workflows/main.yml
updated image push action
NA
Bypassed pushing images to dockerhub for master branch
NA
> updated image push action

- go.mod
- go.sum
Upgraded containerd dependency to incorporate a security fix
> Upgraded containerd dependency to incorporate a security fix

- .github/workflows/main.yml
NA.
Enable workflow triggers in test-at-scale
> added workflow_dispatch

- .github/workflows/main.yml
> updated environment variable syntax

- pkg/core/models.go
- pkg/service/teststats/teststats_test.go
update json keys for test suite payload
> update json keys for test suite payload

- pkg/core/interfaces.go
- pkg/core/lifecycle.go
- pkg/core/models.go
- pkg/global/nucleusconstants.go
- pkg/secret/secret.go
- pkg/secret/secret_test.go
- testutils/mocks/SecretParser.go
[Refresh Token Mechanism](https://lambdatest.atlassian.net/browse/PHX-2613)
Added internal Refresh token API in case of expired token
> added refresh token api

- README.md
updated readme for ambiguity
NA
updated readme for ambiguity
> updated readme for ambiguity

- README.md
NA
Update minor note for hidden file in readme
> updated readme note

- .github/workflows/main.yml
- Fixed goreportcard check failure due to https://github.com/gojp/goreportcard/commit/5aeaec8b44c4446e92e66e23f0e04b24e95da4a5
> Update main.yml (#79)

- .golangci.yml
> uncommented lint configuration

- .golangci.yml
- pkg/azure/client.go
- pkg/core/lifecycle.go
- pkg/errs/nucleus.go
- pkg/gitmanager/setup.go
- pkg/service/teststats/teststats.go
- pkg/service/teststats/teststats_test.go
- pkg/testexecutionservice/testexecution.go
Syncing beta with latest stage - part 2
> Syncing beta with latest stage - part 2

- pkg/gitmanager/setup.go
Fixed private auth in GitLab clone
Tested `git clone` command for both GitHub and GitLab locally with `oauth2:<oauth-access-token>`
> Fixed private auth in GitLab clone

- .gitignore
- Makefile
- docker-compose.yml
- pkg/core/models.go
- pkg/gitmanager/setup.go
- pkg/global/synapseconstants.go
- pkg/runner/docker/docker.go
- pkg/service/teststats/teststats_test.go
- pkg/synapse/synapse.go
> Syncing beta with latest dev

- pkg/gitmanager/setup.go
Fixed private oauth in case of private bitbucket repos
Tested command for a private Bitbucket repo
> Fixed private oauth in case of private bitbucket repos

- pkg/gitmanager/setup.go
Syncing beta with latest dev changes
> Syncing beta with latest dev changes

- pkg/global/synapseconstants.go
https://github.com/LambdaTest/test-at-scale/issues/111
This PR adds mapping of pi env with lambdatest endpoint
> added api endpoint mapping for pi

- pkg/synapse/synapse.go
https://github.com/LambdaTest/test-at-scale/issues/118
Add retry mechanism if there is open connection error 
> retry on  duplicate connection

- .github/workflows/pull_request_lint.yml
- .github/workflows/release.yml
minor ci linting
NA.
- Removed extraline
- added issue linting for all branch
> minor ci linting, added issue linting for all branch

- pkg/blocktestservice/setup_test.go
- pkg/core/lifecycle.go
- pkg/core/models.go
- pkg/testdiscoveryservice/testdiscovery.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Closes: https://github.com/LambdaTest/test-at-scale/issues/138
Add support for file splitting instead of test splitting.
> Test file based splitting feature

- .github/workflows/pull_request_lint.yml
- .github/workflows/release.yml
- Fix cicd to support forked repo
> fix cicd to support forked repo

- pkg/core/models.go
- pkg/testdiscoveryservice/testdiscovery.go
https://github.com/LambdaTest/test-at-scale/issues/133
This PR includes fix for custom nucleus image support
> fix support of custom nucleus image

- Makefile
- pkg/gitmanager/setup.go
- pkg/urlmanager/urlmanager.go
- pkg/urlmanager/urlmanager_test.go
Replaced zip download link with API link
Note: **Support for Github apps**
Fixes # ([GitHub Apps support](https://github.com/LambdaTest/test-at-scale/issues/137))
> changed zip url for github

- pkg/core/lifecycle.go
- pkg/errs/nucleus.go
- pkg/tasconfigmanager/setup.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
N/A Refactor
Fixed certain error remark strings
Tested locally
> Corrected remarks

- pkg/core/models.go
- pkg/service/teststats/teststats_test.go
#156 
Forwarding failureReason captured by runners to TAS Cloud
Tested locally
> #156: Sending failureReason for test failures

- pkg/gitmanager/setup.go
- pkg/global/nucleusconstants.go
#164 
Increased git clone timeout
Logical Fix. Will test on stage.
> #164: Increased git clone timeout

- cmd/nucleus/bin.go
- pkg/azure/client.go
- pkg/blocktestservice/setup.go
- pkg/blocktestservice/setup_test.go
- pkg/core/interfaces.go
- pkg/requestutils/request.go
- pkg/task/task.go
- pkg/testdiscoveryservice/testdiscovery.go
- pkg/testexecutionservice/testexecution.go
- pkg/utils/utils.go
Ticket := [#162 ](https://github.com/LambdaTest/test-at-scale/issues/162)
Added auth feature in the internal routes which verify repoID, OrgID, BuildID with the help of JWT.
> #161: added auth feature in internal routes

- build/nucleus/Dockerfile
#170.
Current docker image contains lot of security related issues. We need to fix the base docker image and try to minimize vulnerability.
> fix: docker image security vulnerability

- go.mod
- pkg/procfs/procfs.go
#176 
Normalized CPU Percent to <= 100 %
Tested on TAS Stage deployment.
> #176: Normalized CPU Percent to <= 100 %

- build/nucleus/Dockerfile
#168
Provide sudo privileges to container user
> sudo privileges to container user

- .github/workflows/pull_request_lint.yml
- build/nucleus/Dockerfile
Updated docker image to include python
Tested on `angular.js` repo which fails without python installed
> Updated docker image to include python

- build/nucleus/Dockerfile
Reverts LambdaTest/test-at-scale#169
> Revert "sudo privileges to container user"

- .sample.synapse.json
NA.
Made synapse.json more user friendly.
> updated sample-synapse.json

- pkg/core/wsproto.go
- pkg/synapse/synapse.go
- pkg/synapse/utils.go
https://github.com/LambdaTest/test-at-scale/issues/186
This PR will add error message in job Info (which will be passed to TAS  ), In case of failure
> added error message in jobInfo

- pkg/blocktestservice/setup_test.go
- pkg/core/lifecycle.go
- pkg/global/nucleusconstants.go
Fetch blocklisted and quarantined tests for each task.
> fetch blocklisted and qurantined tests  for each task

- pkg/core/wsproto.go
- pkg/synapse/synapse.go
NA.
Added support to send synapse version to TAS Cloud.
> added support for synapse version

- pkg/azure/client.go
- pkg/requestutils/request.go
https://github.com/LambdaTest/test-at-scale/issues/194
This PR will fix retry for server side errors 
> fix api retry for offline synapse

- .github/workflows/premerge.yml
- pkg/core/lifecycle.go
- pkg/global/nucleusconstants.go
- pkg/utils/utils.go
https://github.com/LambdaTest/test-at-scale/issues/204
This PR has the following changes
- Version  fix , if no version is mention, the code will now pick 1.0.0 as default version
- Fix blocklist regression in code
> fix yaml version issue and blocklist regression

- README.md
> fixed broken link in doc

- .github/workflows/dockerhub-description.yml
- README.md
NA.
- support for dockerhub page ci; updated doc links.
> docs: support for docker hub page ci and updated links

- .github/workflows/dockerhub-description.yml
NA.
updated dockerhub secrets.
> updated dockerhub secrets

- pkg/global/synapseconstants.go
NA
updated internal endpoint url.
> updated endpoints

- pkg/driver/driver_v2.go
- pkg/driver/driver_v2_test.go
https://github.com/LambdaTest/test-at-scale/issues/218
This PR will fix smart selection for multi config
> fix smart selection in multiconfig

- pkg/core/runner.go
- pkg/core/wsproto.go
- pkg/gitmanager/setup_test.go
- pkg/runner/docker/docker.go
- pkg/synapse/synapse.go
https://github.com/LambdaTest/test-at-scale/issues/202
Added functionality to abort builds on synapse.
> [Feature]: Aborting jobs on synapse

- pkg/core/interfaces.go
- pkg/driver/driver_v1.go
- pkg/driver/driver_v2.go
- pkg/tasconfigdownloader/setup.go
- pkg/tasconfigmanager/setup.go
- pkg/tasconfigmanager/setup_test.go
This PR will fix yml segregation remarks 
https://github.com/LambdaTest/test-at-scale/issues/224
> fix remarks for tas yml segregation

- pkg/global/nucleusconstants.go
- pkg/tasconfigdownloader/setup.go
- pkg/tasconfigmanager/setup.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
https://github.com/LambdaTest/test-at-scale/issues/230
Correction of remarks if there is mismatch between TAS structure and version
> fix remark for version mismatch
